spring:
  application:
    name: order

order:
  rest:
    client:
      connection-timeout: 5000
      read-timeout: 5000

user-profile:
  base-url: http://localhost:8080/user/api

merchant-profile:
  base-url: http://localhost:8081/merchant/api

fundiin:
  base-url: https://gateway-qa.fundiin.vn
  initiate-order-path: /v2/payments
  client-id: HOIBANTRON
  signature: at67qH6mk8w5Y1nAyMoYKMWACiEi2bsa
