spring:

  application:
    name: order

  datasource:
    url: jdbc:postgresql://localhost:5432/event_booking_system?currentSchema=udpt_platform
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: 27017
      database: QTSCDLHD
    redis:
      host: secret
      password: secret
      database: 3
      lettuce:
        pool:
          max-active: 100
          max-idle: 10
          min-idle: 2
          ## Maximum connection waiting time.
          max-wait: 3000
      timeout: 60000
      port: 6379

order:
  rest:
    client:
      connection-timeout: 5000
      read-timeout: 5000

user-profile:
  base-url: http://localhost:8081/user-profiles

merchant-profile:
  base-url: http://10.124.7.184:7253/api/merchant-profiles

fundiin:
  base-url: https://gateway-qa.fundiin.vn
  initiate-order-path: /v2/payments
  client-id: HOIBANTRON
  signature: at67qH6mk8w5Y1nAyMoYKMWACiEi2bsa

momo:
  base-url: https://test-payment.momo.vn
  initiate-order-path: /v2/gateway/api/create